import { MantineProvider, createTheme } from "@mantine/core";
import { DM_Sans } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import StoreWrapper from "@/wrapper/storeWrapper";
import { ToastContainer } from "@/services/toastMessages";
import ReactQueryProvider from "@/wrapper/queryClientWrapper";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: [ "latin" ],
  weight: [ "400", "500", "700" ],
});


export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className} suppressHydrationWarning>
        <ReactQueryProvider>
          <StoreWrapper>
            <ToastContainer />
            <MantineProvider theme={createTheme()}>
              {children}
            </MantineProvider>
          </StoreWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
